### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by thedjpetersen** [imduffy15/mifit-exporter#3]
Thank you for this project! I've been working on getting my data out and backed up and it was this one which cracked the nut for me :)

**Comment by matisiekpl** [comment]
@thedjpetersen 
I also was finding a way to export activities to GPX and I found this great repo. It inspired me to create an app for comfortable exporting activities without PC: Mi Fit Exporter
Android: https://play.google.com/store/apps/details?id=pl.enteam.mifit_gpx_exporter
iOS: Coming soon....
Thanks @imduffy15 for this!

**Comment by imduffy15** [comment]
Thanks for sharing. Check out the amazfit app too. It enables you to configure your watch to sync directly to strava.
